scrape_configs:
   - job_name: 'User Authorization Service input'
     metrics_path: '/api/v1.0/moviebooking/actuator/prometheus'
     scrape_interval: 3s
     static_configs:
      - targets: ['127.0.0.1:8081']
        labels:
          application: 'User Authorization Service'