scrape_configs:
  - job_name: 'Admin Service input'
    metrics_path: '/api/v1.0/moviebooking/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8084']
        labels:
          application: 'Admin Service'