scrape_configs:
  - job_name: 'Movie Catalog Service input'
    metrics_path: '/api/v1.0/moviebooking/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'Movie Catalog Service'